spring.application.name=batch


spring.batch.job.enabled=true
spring.batch.initialize-schema=always

input.file.path=input.csv
output.ok.file=resultatok.csv
output.t01.file=anomalieT01.csv
output.t19.file=anomalieT19.csv
output.topo.file=anomalieCodeTopo.csv

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
